### ISSUE TITLE
Some thoughts; UUID and return user ID

### ISSUE THREAD

**Issue by Padchi** [simplabs/rails_api_auth#22]
First, great gem! Made my day much simpler, except this:
My User model use UUID and some how I can still get the login for a user but still thinks this is wrong and will throw a error at somehow? (User.id and Login.user_id)

```
  User Load (0.3ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1
 => #<User id: "75f01ba9-20c0-42c5-a635-9b02bcb79114" ...> 
2.2.3 :013 > u.login
  Login Load (0.2ms)  SELECT  "logins".* FROM "logins" WHERE "logins"."user_id" = $1 LIMIT 1  [["user_id", 75]]
 => #<Login ... user_id: 75> 
```

And why don't return the user id with the access_token on POST /token?

**Comment by marcoow** [comment]
UUID isn't really supported yet. You'd have to manually add a migration that changes the foreign key column's type on the `logins` table. Maybe you'll also want to change the `login` table's id column as well so that's more consistent in the DB. If you figure out a way to somehow build that into the engine we'd appreciate a PR!

Regarding having the user id in the response: the engine wants to be compliant with the spec and that is pretty clear about the response and the data it includes. The user id is just not defined there. We usually have a special route `/users/me` or so where authenticated users would receive their own user record and which we call right after the authentication succeeds.

**Comment by Padchi** [comment]
Wow thats a fast response! Tried to find you on slack cuz we planning to release our new site tomorrow but with that answer i can still follow the schedule ;)

Maybe a init script for this gem would be nice and then pass a `--uuid` argument?

I haven't read the spec but if thats so i will go with the `user/me` and tbh i think that's the best approach too. Maybe some documentations for this tho for new users? I guess that some new users that want to build a ember frontend and a rails backend will find this gem so a documentation on `users/me` would be great. Especially when this gem works fine with both ember-simple-auth and torii standalone

**Comment by marcoow** [comment]
Yeah, moving the migration into a generator that accepts a `--uuid` argument would probably be the cleanest solution - PR would be appreciated!

A PR adding the info about `/users/me` to the README would be great as well of course.

**Comment by Padchi** [comment]
I will do my best after our release. Got some problem withe the include but it's probably something I'm doing wrong. It won't find the include 

Skickat från min iPhone
